### ISSUE TITLE
Certify this implementation

### ISSUE THREAD

**Issue by Thihup** [ggeorgovassilis/fauxjsp#16]
Hi. Do you plan to certify this implementation? I can help you setting up the TCK if you would like. 

However, the current specification of JSP (Jakarta Server Pages) did a rename from javax to jakarta. So it would require renaming the namespace from javax to jakarta.

https://www.agilejava.eu/2021/02/05/compatible-implementations/
https://jakarta.ee/specifications/pages/3.0/

**Comment by ggeorgovassilis** [comment]
I would love that, but I don't see it happening. Tags in JSP rely on a factory pattern which produces code which produces page content. Fauxjsp renders JSP directly to content, skipping the interpediate factory step. This is not only an impementation detail, it means that 3rd party tag libraries cannot be used with JSP.

**Comment by Thihup** [comment]
Oh, I see. Thanks anyway :)
